name: MacOS build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - px4_fmu-v5_default
          - px4_sitl
          # tests (includes px4_sitl)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          ./Tools/setup/macos.sh
          ./Tools/setup/macos.sh

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          echo "timestamp=$(date -u +'%Y-%m-%d-%H;%M;%S')" >> $GITHUB_ENV

      - name: ccache cache files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: macos_${{ matrix.config }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: macos_${{ matrix.config }}-ccache-

      - name: Setup ccache
        run: |
          mkdir -p ~/.ccache
          echo "base_dir = ${GITHUB_WORKSPACE}" > ~/.ccache/ccache.conf
          echo "compression = true" >> ~/.ccache/ccache.conf
          echo "compression_level = 6" >> ~/.ccache/ccache.conf
          echo "max_size = 40M" >> ~/.ccache/ccache.conf
          echo "hash_dir = false" >> ~/.ccache/ccache.conf
          ccache -s
          ccache -z

      - name: Build ${{ matrix.config }}
        run: |
          ccache -z
          make ${{ matrix.config }}
          ccache -s
